// class Subreddit {
//   final String subreddit, alias;

//   Subreddit(this.subreddit, this.alias);
// }

List<String> initialSubredditsList = [
  'mobilewallpapers',
  'Amoledbackgrounds',
  'phonewallpapers',
  'Verticalwallpapers',
  'MinimalWallpaper',
  'wallpapers',
  'phonewallpaper',
  'AnimeWallpaper',
  'iWallpaper',
  'wallpaper',
  'iPhoneWallpapers',
  'WQHD_Wallpaper',
  'S10Wallpapers',
  'MobileWallpaper',
];

// List<Subreddit> kTotalSubreddits = [
//   Subreddit('wallpapers', 'Wallpaper'),
//   Subreddit('mobilewallpapers', 'MobileWallpaper'),
//   Subreddit('Amoledbackgrounds', 'AmoledWalls'),
//   Subreddit('MinimalWallpaper', 'MinimalWalls'),
//   Subreddit('Verticalwallpapers', 'VerticalWalls'),
//   Subreddit('phonewallpapers', 'PhoneWallpapers'),
//   Subreddit('phonewallpaper', 'PhoneWallpaper'),
//   Subreddit('AnimeWallpaper', 'Anime'),
//   Subreddit('iWallpaper', 'iWallpaper'),
//   Subreddit('wallpaper', 'Wallpaper'),
//   Subreddit('iPhoneWallpapers', 'iPhone'),
//   Subreddit('WQHD_Wallpaper', 'WQHD'),
//   Subreddit('S10Wallpapers', 'S10Wallpapers'),
//   Subreddit('MobileWallpaper', 'MobileWallpaper'),

// Subreddit('EarthPorn', 'Earth'),
// Subreddit('hiphopwallpapers', 'Wallpaper'),
// Subreddit('botanicalPorn', 'Wallpaper'),
// Subreddit('waterPorn', 'Water'),
// Subreddit('seaPorn', 'Sea'),
// Subreddit('skyPorn', 'Sky'),
// Subreddit('firePorn', 'Fire'),
// Subreddit('desertPorn', 'Desert'),
// Subreddit('winterPorn', 'Winter'),
// Subreddit('autumnPorn', 'Autumn'),
// Subreddit('weatherPorn', 'Weather'),
// Subreddit('geologyPorn', 'Geology'),
// Subreddit('spacePorn', 'Space'),
// Subreddit('Beach', 'Wallpaper'),
// Subreddit('mushroomPorn', 'Mushroom'),
// Subreddit('springPorn', 'Spring'),
// Subreddit('summerPorn', 'Summer'),
// Subreddit('lavaPorn', 'Lava'),
// Subreddit('lakePorn', 'Lake'),
// Subreddit('cityPorn', 'City'),
// Subreddit('villagePorn', 'Village'),
// Subreddit('ruralPorn', 'Rural'),
// Subreddit('architecturePorn', 'Architecture'),
// Subreddit('housePorn', 'House'),
// Subreddit('cabinPorn', 'Cabin'),
// Subreddit('churchPorn', 'Church'),
// Subreddit('abandonedPorn', 'Abandoned'),
// Subreddit('cemeteryPorn', 'Cemetery'),
// Subreddit('infrastrucurePorn', 'Infrastructure'),
// Subreddit('machinePorn', 'Machine'),
// Subreddit('carPorn', 'Car'),
// Subreddit('f1Porn', 'F1'),
// Subreddit('motorcyclePorn', 'Motorcycle'),
// Subreddit('militaryPorn', 'Military'),
// Subreddit('gunPorn', 'Gun'),
// Subreddit('knifePorn', 'Knife'),
// Subreddit('boatPorn', 'Boat'),
// Subreddit('ridesPorn', 'Rides'),
// Subreddit('destructionPorn', 'Destruction'),
// Subreddit('thingsCutInHalfPorn', 'Things Cut in Half'),
// Subreddit('starshipPorn', 'Wallpaper'),
// Subreddit('toolPorn', 'StarShip'),
// Subreddit('technologyPorn', 'Technology'),
// Subreddit('bridgePorn', 'Bridge'),
// Subreddit('policePorn', 'Police'),
// Subreddit('steamPorn', 'Steam'),
// Subreddit('retailPorn', 'retail'),
// Subreddit('spaceFlightPorn', 'SpaceFlight'),
// Subreddit('roadPorn', 'Road'),
// Subreddit('dryDockPron', 'Dry Dock'),
// Subreddit('animalPorn', 'Animals'),
// Subreddit('humanPorn', 'Humans'),
// Subreddit('earthlingPorn', 'Earthlings'),
// Subreddit('climbingPorn', 'Climbing'),
// Subreddit('sportsPorn', 'Sports'),
// Subreddit('foodPorn', 'Food'),
// Subreddit('cullinaryPorn', 'Cullinary'),
// Subreddit('moviePosterPorn', 'Movie Poster'),
// Subreddit('televisionPosterPorn', 'Television Poster'),
// Subreddit('comicbookPorn', 'ComicBook'),
// Subreddit('streetArtPorn', 'Street Art'),
// Subreddit('macroPorn', 'Macro'),
// Subreddit('microPorn', 'Micro'),
// Subreddit('geekPorn', 'Geek'),
// ];
